name: Build and Test Workflow

on:
 push:
    branches:
        - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dep.
        run: |
          python -m pip install --upgrade pip
          pip install -r ././requirements.txt
        
      - name: Run build
        run: |
          python setup.py build  

      - name: Run test
        run: |
          pytest tests/



